# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            curl -sL https://cmake.org/files/v3.15/cmake-3.15.3-Linux-x86_64.sh -o cmakeinstall.sh
            chmod +x cmakeinstall.sh
            sudo ./cmakeinstall.sh --prefix=/usr/local --exclude-subdir
            rm cmakeinstall.sh
            git submodule update --init --recursive
            git lfs install
            git lfs pull
            sudo apt -y install libx11-dev libxrandr-dev libxi-dev libxinerama-dev libxcursor-dev libudev-dev
            sudo apt -y install libssl-dev

      - task: CMake@1
        inputs:
          cmakeArgs: '.. -DBUILD_TEST=ON'

      - task: CMake@1
        inputs:
          cmakeArgs: '--build . --config Release'
